
import React, { useMemo, useState, useEffect, useRef } from 'react';
import { Client, Declaration, DeclarationStatus, ReceiptData, TaxRegime, ClientCategory } from '../types';
import { getDueDateForPeriod, formatPeriodForDisplay, getPeriod } from '../services/sri';
import { getClientServiceFee } from '../services/clientService';
import { differenceInCalendarDays, isSameMonth, parseISO, isValid, subMonths, startOfMonth, format } from 'date-fns';
import { es } from 'date-fns/locale';
import { 
    AlertTriangle, CheckCircle, MessageSquare, Mail, Info, DollarSign, 
    Printer, Clipboard, Search, Loader, CreditCard, X, TrendingUp, 
    Wallet, Briefcase, Clock, Layers, Calendar as CalendarIcon, Filter,
    CheckSquare, Square
} from 'lucide-react';
import { useToast } from '../context/ToastContext';
import { useAppStore } from '../store/useAppStore';
import { Modal } from '../components/Modal';
import { printSalesNote } from '../services/printService';
import { PieChart, Pie, Legend, ResponsiveContainer, Cell, Tooltip } from 'recharts';

interface CobranzaScreenProps {
    autoRegister?: boolean;
    clearAutoAction?: () => void;
}

type TabView = 'receivable' | 'projected' | 'collected';
type ObligationFilter = 'all' | 'mensual' | 'semestral' | 'renta';

interface FinancialItem {
    clientId: string;
    clientName: string;
    ruc: string;
    period: string;
    amount: number;
    status: DeclarationStatus;
    type: 'mensual' | 'semestral' | 'renta' | 'dev';
    dateReference: Date; 
    daysDiff?: number;
    phones: string[];
    isVirtual?: boolean; // Indicates if this debt was auto-generated by the audit engine
}

export const CobranzaScreen: React.FC<CobranzaScreenProps> = ({ autoRegister, clearAutoAction }) => {
    const { clients, setClients, serviceFees, businessProfile } = useAppStore();
    const { toast } = useToast();

    // UI States
    const [activeTab, setActiveTab] = useState<TabView>('receivable');
    const [obligationFilter, setObligationFilter] = useState<ObligationFilter>('all');
    const [selectedMonth, setSelectedMonth] = useState(new Date());
    const [searchTerm, setSearchTerm] = useState('');
    
    // Actions State
    const [selectedItems, setSelectedItems] = useState<Set<string>>(new Set()); 
    const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
    const [paymentMethod, setPaymentMethod] = useState('Transferencia');
    const [isProcessing, setIsProcessing] = useState(false);
    
    // Receipt Logic
    const [receiptData, setReceiptData] = useState<ReceiptData | null>(null);
    const [isReceiptOpen, setIsReceiptOpen] = useState(false);
    const receiptRef = useRef<HTMLDivElement>(null);

    // --- FINANCIAL AUDIT ENGINE ---
    const financialData = useMemo(() => {
        const receivable: FinancialItem[] = [];
        const projected: FinancialItem[] = [];
        const collected: FinancialItem[] = [];
        const now = new Date();

        clients.forEach(client => {
            // Skip fully inactive clients or deleted ones
            if (client.isDeleted || client.isActive === false) return;

            const fee = getClientServiceFee(client, serviceFees);
            
            // Determine Type Logic
            let type: FinancialItem['type'] = 'mensual';
            if (client.category.includes('Semestral') || client.regime === TaxRegime.RimpeEmprendedor) type = 'semestral';
            else if (client.regime === TaxRegime.RimpeNegocioPopular) type = 'renta';
            else if (client.category.includes('Devolución')) type = 'dev';

            // Global Filter application
            if (obligationFilter !== 'all' && type !== obligationFilter && !(obligationFilter === 'renta' && type === 'dev')) return;

            // 1. RECOLECTAR HISTORIAL (Pagado y Pendiente Explícito)
            const historyMap = new Set<string>(); // To track what we already have

            client.declarationHistory.forEach(decl => {
                historyMap.add(decl.period);

                if (decl.status === DeclarationStatus.Pagada && decl.paidAt) {
                    // COLLECTED LOGIC
                    const paidDate = parseISO(decl.paidAt);
                    if (isValid(paidDate) && isSameMonth(paidDate, selectedMonth)) {
                        collected.push({
                            clientId: client.id,
                            clientName: client.name,
                            ruc: client.ruc,
                            period: decl.period,
                            amount: decl.amount || fee,
                            status: DeclarationStatus.Pagada,
                            type,
                            dateReference: paidDate,
                            phones: client.phones || []
                        });
                    }
                } else if (decl.status !== DeclarationStatus.Pagada) {
                    // RECEIVABLE (Explicit) LOGIC
                    const dueDate = getDueDateForPeriod(client, decl.period);
                    const isOverdue = dueDate ? differenceInCalendarDays(now, dueDate) > 0 : false;
                    
                    // If sent or overdue, it's receivable. If standard pending, it's projected/receivable depending on date
                    receivable.push({
                        clientId: client.id,
                        clientName: client.name,
                        ruc: client.ruc,
                        period: decl.period,
                        amount: decl.amount || fee,
                        status: decl.status,
                        type,
                        dateReference: dueDate || now,
                        daysDiff: dueDate ? differenceInCalendarDays(now, dueDate) : 0,
                        phones: client.phones || []
                    });
                }
            });

            // 2. DETECTAR VACÍOS (Deudas Implícitas / "Ghost Debts")
            // This fixes the "Alan" issue. Even if history is empty, we check if they SHOULD have a declaration.
            
            // Generate expected periods for the last 3 months + current
            const periodsToCheck: string[] = [];
            
            if (type === 'mensual' || type === 'dev') {
                // Check current month (Projection)
                const currentP = getPeriod(client, now);
                periodsToCheck.push(currentP);
                // Check previous month (Receivable)
                const prevDate = subMonths(now, 1);
                const prevP = getPeriod(client, prevDate);
                if (prevP !== currentP) periodsToCheck.push(prevP);
            } else if (type === 'semestral') {
                const currentP = getPeriod(client, now);
                periodsToCheck.push(currentP);
            }

            periodsToCheck.forEach(p => {
                if (!historyMap.has(p)) {
                    const dueDate = getDueDateForPeriod(client, p);
                    const daysDiff = dueDate ? differenceInCalendarDays(now, dueDate) : -99;
                    
                    // Logic: 
                    // If overdue (>0 days diff), it's RECEIVABLE (Real Debt).
                    // If future/current (<=0 days diff), it's PROJECTED.
                    
                    const item: FinancialItem = {
                        clientId: client.id,
                        clientName: client.name,
                        ruc: client.ruc,
                        period: p,
                        amount: fee,
                        status: DeclarationStatus.Pendiente,
                        type,
                        dateReference: dueDate || now,
                        daysDiff: daysDiff,
                        phones: client.phones || [],
                        isVirtual: true // Mark as auto-generated
                    };

                    if (daysDiff > 0) {
                        receivable.push(item); // It's late! You owe me!
                    } else {
                        projected.push(item); // Coming soon
                    }
                }
            });
        });

        // Sorting
        receivable.sort((a, b) => (b.daysDiff || 0) - (a.daysDiff || 0)); // Most overdue first
        collected.sort((a, b) => b.dateReference.getTime() - a.dateReference.getTime());
        projected.sort((a, b) => a.clientName.localeCompare(b.clientName));

        return { receivable, projected, collected };
    }, [clients, serviceFees, obligationFilter, selectedMonth]);

    // Filtering by Search Term
    const getFilteredList = (list: FinancialItem[]) => {
        if (!searchTerm) return list;
        const lower = searchTerm.toLowerCase();
        return list.filter(i => i.clientName.toLowerCase().includes(lower) || i.ruc.includes(lower));
    };

    const currentList = useMemo(() => {
        switch(activeTab) {
            case 'receivable': return getFilteredList(financialData.receivable);
            case 'projected': return getFilteredList(financialData.projected);
            case 'collected': return getFilteredList(financialData.collected);
            default: return [];
        }
    }, [activeTab, financialData, searchTerm]);

    const totalAmount = useMemo(() => currentList.reduce((sum, item) => sum + item.amount, 0), [currentList]);

    // --- CHART DATA ---
    const pieData = useMemo(() => {
        const data = [
            { name: 'Mensual', value: 0, fill: '#3b82f6' },
            { name: 'Semestral', value: 0, fill: '#8b5cf6' },
            { name: 'Renta', value: 0, fill: '#f59e0b' },
        ];
        
        const sourceList = activeTab === 'collected' ? financialData.collected : (activeTab === 'receivable' ? financialData.receivable : financialData.projected);
        
        sourceList.forEach(item => {
            if (item.type === 'mensual' || item.type === 'dev') data[0].value += item.amount;
            else if (item.type === 'semestral') data[1].value += item.amount;
            else data[2].value += item.amount;
        });
        
        return data.filter(d => d.value > 0);
    }, [financialData, activeTab]);

    // --- HANDLERS ---
    
    const handleToggleSelect = (key: string) => {
        const newSet = new Set(selectedItems);
        if (newSet.has(key)) newSet.delete(key);
        else newSet.add(key);
        setSelectedItems(newSet);
    };

    const handleSelectAll = () => {
        if (selectedItems.size === currentList.length) setSelectedItems(new Set());
        else setSelectedItems(new Set(currentList.map(i => `${i.clientId}-${i.period}`)));
    };

    const handleProcessPayment = () => {
        if (selectedItems.size === 0) return;
        setIsProcessing(true);
        
        const now = new Date().toISOString();
        const transactionId = `PAY-${Date.now().toString().slice(-6)}`;
        let totalPaid = 0;
        let lastClient: Client | null = null;
        let paidPeriods: any[] = [];

        // We need to handle both existing declarations and Virtual ones
        const newClients = clients.map(client => {
            let clientModified = false;
            let currentHistory = [...client.declarationHistory];

            // Check if any selected item belongs to this client
            const clientSelectedItems = currentList.filter(i => i.clientId === client.id && selectedItems.has(`${i.clientId}-${i.period}`));
            
            if (clientSelectedItems.length > 0) {
                clientModified = true;
                clientSelectedItems.forEach(item => {
                    const existingDeclIndex = currentHistory.findIndex(d => d.period === item.period);
                    
                    const amount = item.amount;
                    totalPaid += amount;
                    paidPeriods.push({ period: item.period, amount });

                    if (existingDeclIndex > -1) {
                        // Update existing
                        currentHistory[existingDeclIndex] = {
                            ...currentHistory[existingDeclIndex],
                            status: DeclarationStatus.Pagada,
                            paidAt: now,
                            transactionId,
                            amount
                        };
                    } else {
                        // Create new (from Virtual/Projected)
                        currentHistory.push({
                            period: item.period,
                            status: DeclarationStatus.Pagada,
                            updatedAt: now,
                            paidAt: now,
                            declaredAt: now, // Assume declared if paid
                            transactionId,
                            amount
                        });
                    }
                });
            }

            if (clientModified) {
                const updatedClient = { ...client, declarationHistory: currentHistory };
                lastClient = updatedClient; // For receipt
                return updatedClient;
            }
            return client;
        });

        setTimeout(() => {
            setClients(newClients);
            setIsProcessing(false);
            setIsPaymentModalOpen(false);
            setSelectedItems(new Set());
            
            // Generate Receipt if single client batch, otherwise just toast
            // For logic simplicity here, if multiple clients paid, we show receipt for the last one or a summary
            if (lastClient && paidPeriods.length > 0) {
                 setReceiptData({
                    transactionId,
                    clientName: lastClient.name,
                    clientRuc: lastClient.ruc,
                    client: lastClient,
                    paymentDate: format(new Date(), 'dd MMMM yyyy, HH:mm', { locale: es }),
                    paidPeriods: paidPeriods,
                    totalAmount: totalPaid
                });
                setIsReceiptOpen(true);
            }
            
            toast.success(`Cobro registrado: $${totalPaid.toFixed(2)}`);
        }, 800);
    };

    const handleWhatsAppNotify = (item: FinancialItem) => {
        if (!item.phones[0]) {
            toast.warning("El cliente no tiene teléfono registrado.");
            return;
        }
        const phone = item.phones[0].replace(/\D/g, '');
        const fullPhone = phone.startsWith('593') ? phone : `593${phone.substring(1)}`;
        
        let message = '';
        if (activeTab === 'receivable') {
            message = `Estimado/a ${item.clientName}, le recordamos que tiene un saldo pendiente de $${item.amount.toFixed(2)} correspondiente al periodo ${formatPeriodForDisplay(item.period)}.`;
        } else if (activeTab === 'projected') {
            message = `Estimado/a ${item.clientName}, se aproxima su declaración de ${formatPeriodForDisplay(item.period)}. Valor estimado: $${item.amount.toFixed(2)}.`;
        } else {
             message = `Estimado/a ${item.clientName}, confirmamos la recepción de su pago por ${formatPeriodForDisplay(item.period)}. Gracias por su confianza.`;
        }
        
        window.open(`https://wa.me/${fullPhone}?text=${encodeURIComponent(message)}`, '_blank');
    };

    return (
        <div className="pb-20 animate-fade-in space-y-6">
            
            {/* Header & Main Stats */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
                <div>
                    <h2 className="text-3xl font-display font-black text-brand-navy dark:text-white flex items-center gap-2">
                        <Wallet className="text-gold"/> Gestión de Cobranza
                    </h2>
                    <p className="text-slate-500 font-medium text-sm mt-1">Control financiero y conciliación inteligente.</p>
                </div>
                
                {/* Global Summary Cards */}
                 <div className="flex gap-4 w-full md:w-auto overflow-x-auto pb-2 md:pb-0">
                    <div className="bg-white dark:bg-slate-900 p-4 rounded-2xl border border-red-100 dark:border-red-900/30 shadow-sm min-w-[160px]">
                        <div className="flex items-center gap-2 mb-1">
                            <div className="w-2 h-2 rounded-full bg-red-500"></div>
                            <span className="text-xs font-bold text-slate-500 uppercase">Por Cobrar</span>
                        </div>
                        <p className="text-xl font-black text-slate-800 dark:text-white">
                            ${financialData.receivable.reduce((s, i) => s + i.amount, 0).toFixed(2)}
                        </p>
                    </div>
                    <div className="bg-white dark:bg-slate-900 p-4 rounded-2xl border border-blue-100 dark:border-blue-900/30 shadow-sm min-w-[160px]">
                        <div className="flex items-center gap-2 mb-1">
                            <div className="w-2 h-2 rounded-full bg-blue-500"></div>
                            <span className="text-xs font-bold text-slate-500 uppercase">Proyección</span>
                        </div>
                        <p className="text-xl font-black text-slate-800 dark:text-white">
                             ${financialData.projected.reduce((s, i) => s + i.amount, 0).toFixed(2)}
                        </p>
                    </div>
                    <div className="bg-gradient-to-br from-emerald-500 to-teal-600 p-4 rounded-2xl shadow-lg min-w-[160px] text-white">
                        <div className="flex items-center gap-2 mb-1">
                            <CheckCircle size={12} fill="currentColor" className="text-emerald-800"/>
                            <span className="text-xs font-bold uppercase opacity-90">Recaudado</span>
                        </div>
                        <p className="text-xl font-black">
                            ${financialData.collected.reduce((s, i) => s + i.amount, 0).toFixed(2)}
                        </p>
                    </div>
                </div>
            </div>

            {/* Controls Bar */}
            <div className="flex flex-col lg:flex-row gap-4 justify-between items-center bg-white dark:bg-slate-900 p-2 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-800">
                {/* Tabs */}
                <div className="flex p-1 bg-slate-100 dark:bg-slate-800 rounded-xl w-full lg:w-auto">
                    <button onClick={() => setActiveTab('receivable')} className={`flex-1 lg:flex-none px-6 py-2 rounded-lg text-xs font-bold transition-all flex items-center justify-center gap-2 ${activeTab === 'receivable' ? 'bg-white dark:bg-slate-700 text-red-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
                        <AlertTriangle size={14}/> Por Cobrar
                    </button>
                    <button onClick={() => setActiveTab('projected')} className={`flex-1 lg:flex-none px-6 py-2 rounded-lg text-xs font-bold transition-all flex items-center justify-center gap-2 ${activeTab === 'projected' ? 'bg-white dark:bg-slate-700 text-blue-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
                        <TrendingUp size={14}/> Proyección
                    </button>
                    <button onClick={() => setActiveTab('collected')} className={`flex-1 lg:flex-none px-6 py-2 rounded-lg text-xs font-bold transition-all flex items-center justify-center gap-2 ${activeTab === 'collected' ? 'bg-white dark:bg-slate-700 text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
                        <Wallet size={14}/> Ingresos
                    </button>
                </div>

                {/* Filters */}
                <div className="flex items-center gap-2 w-full lg:w-auto overflow-x-auto">
                    <div className="relative flex-1 lg:w-64">
                         <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                        <input 
                            type="text" 
                            placeholder="Buscar cliente, RUC..."
                            value={searchTerm}
                            onChange={e => setSearchTerm(e.target.value)}
                            className="w-full pl-9 py-2 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-xs outline-none focus:ring-2 focus:ring-brand-teal"
                        />
                    </div>
                    
                    <div className="flex gap-1">
                        <button onClick={() => setObligationFilter('all')} className={`px-3 py-2 rounded-lg text-xs font-bold border transition-all ${obligationFilter === 'all' ? 'bg-slate-800 text-white border-slate-800' : 'bg-white border-slate-200 text-slate-500'}`}>Todo</button>
                        <button onClick={() => setObligationFilter('mensual')} className={`px-3 py-2 rounded-lg text-xs font-bold border transition-all ${obligationFilter === 'mensual' ? 'bg-blue-100 text-blue-700 border-blue-200' : 'bg-white border-slate-200 text-slate-500'}`}>Mensual</button>
                        <button onClick={() => setObligationFilter('renta')} className={`px-3 py-2 rounded-lg text-xs font-bold border transition-all ${obligationFilter === 'renta' ? 'bg-orange-100 text-orange-700 border-orange-200' : 'bg-white border-slate-200 text-slate-500'}`}>Renta</button>
                    </div>
                </div>
            </div>

            {/* Main Content Split */}
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
                
                {/* LEFT: Financial Breakdown Chart */}
                <div className="lg:col-span-1 bg-white dark:bg-slate-900 rounded-2xl p-5 shadow-sm border border-slate-100 dark:border-slate-800 h-fit">
                    <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">Composición</h4>
                    <div className="h-48 w-full relative">
                        <ResponsiveContainer width="100%" height="100%">
                            <PieChart>
                                <Pie
                                    data={pieData}
                                    cx="50%"
                                    cy="50%"
                                    innerRadius={40}
                                    outerRadius={60}
                                    paddingAngle={5}
                                    dataKey="value"
                                >
                                    {pieData.map((entry, index) => (
                                        <Cell key={`cell-${index}`} fill={entry.fill} />
                                    ))}
                                </Pie>
                                <Tooltip formatter={(value: number) => `$${value.toFixed(2)}`} />
                                <Legend verticalAlign="bottom" height={36} iconSize={8} wrapperStyle={{fontSize: '10px'}}/>
                            </PieChart>
                        </ResponsiveContainer>
                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-center">
                            <p className="text-[10px] text-slate-400 font-bold">Total</p>
                            <p className="text-sm font-black text-slate-800 dark:text-white">${totalAmount.toFixed(0)}</p>
                        </div>
                    </div>

                    {activeTab !== 'collected' && selectedItems.size > 0 && (
                        <div className="mt-6 pt-6 border-t border-slate-100 dark:border-slate-700 animate-fade-in-up">
                            <p className="text-xs text-slate-500 mb-2 font-medium">Seleccionados: <strong className="text-slate-800 dark:text-white">{selectedItems.size}</strong></p>
                            <button 
                                onClick={() => setIsPaymentModalOpen(true)}
                                className="w-full py-3 bg-brand-teal hover:bg-teal-600 text-white rounded-xl font-bold shadow-lg shadow-teal-500/20 transition-all flex items-center justify-center gap-2 text-sm"
                            >
                                <DollarSign size={16}/> Registrar Pago
                            </button>
                        </div>
                    )}
                </div>

                {/* RIGHT: List View */}
                <div className="lg:col-span-3 bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-800 overflow-hidden flex flex-col min-h-[500px]">
                    {/* List Header */}
                    <div className="grid grid-cols-12 gap-4 p-4 border-b border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 text-[10px] font-black text-slate-400 uppercase tracking-wider items-center">
                        <div className="col-span-1 text-center">
                            <button onClick={handleSelectAll}>
                                {selectedItems.size === currentList.length && currentList.length > 0 ? <CheckSquare size={16} className="text-brand-teal"/> : <Square size={16}/>}
                            </button>
                        </div>
                        <div className="col-span-4">Cliente / RUC</div>
                        <div className="col-span-3 text-center">Periodo</div>
                        <div className="col-span-2 text-right">Monto</div>
                        <div className="col-span-2 text-center">Acción</div>
                    </div>

                    {/* List Items */}
                    <div className="flex-1 overflow-y-auto max-h-[600px]">
                        {currentList.length > 0 ? currentList.map((item, idx) => {
                            const key = `${item.clientId}-${item.period}`;
                            const isSelected = selectedItems.has(key);
                            
                            return (
                                <div key={key} className={`grid grid-cols-12 gap-4 p-4 border-b border-slate-100 dark:border-slate-800 items-center hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors group ${isSelected ? 'bg-blue-50/30 dark:bg-blue-900/10' : ''}`}>
                                    <div className="col-span-1 text-center">
                                        {activeTab !== 'collected' && (
                                            <button onClick={() => handleToggleSelect(key)} className={`${isSelected ? 'text-brand-teal' : 'text-slate-300 hover:text-slate-500'}`}>
                                                {isSelected ? <CheckSquare size={16}/> : <Square size={16}/>}
                                            </button>
                                        )}
                                        {activeTab === 'collected' && <CheckCircle size={16} className="text-emerald-400 mx-auto"/>}
                                    </div>
                                    <div className="col-span-4">
                                        <p className="font-bold text-slate-800 dark:text-white text-sm truncate">{item.clientName}</p>
                                        <p className="font-mono text-xs text-slate-400">{item.ruc}</p>
                                    </div>
                                    <div className="col-span-3 text-center">
                                        <span className="text-xs font-bold bg-slate-100 dark:bg-slate-800 px-2 py-1 rounded text-slate-600 dark:text-slate-300">
                                            {formatPeriodForDisplay(item.period)}
                                        </span>
                                        {item.daysDiff !== undefined && item.daysDiff > 0 && activeTab === 'receivable' && (
                                            <div className="text-[9px] text-red-500 font-bold mt-1 flex items-center justify-center gap-1">
                                                {item.isVirtual && <Info size={8}/>}
                                                Hace {item.daysDiff} días
                                            </div>
                                        )}
                                        {item.isVirtual && activeTab === 'projected' && (
                                             <div className="text-[9px] text-blue-500 font-bold mt-1">Próximo</div>
                                        )}
                                    </div>
                                    <div className="col-span-2 text-right">
                                        <p className="font-mono font-bold text-slate-700 dark:text-white">${item.amount.toFixed(2)}</p>
                                    </div>
                                    <div className="col-span-2 flex justify-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                        <button onClick={() => handleWhatsAppNotify(item)} className="p-1.5 bg-green-100 text-green-600 rounded-lg hover:bg-green-200 transition-colors">
                                            <MessageSquare size={14}/>
                                        </button>
                                        {activeTab === 'collected' && (
                                            <button className="p-1.5 bg-blue-100 text-blue-600 rounded-lg hover:bg-blue-200 transition-colors">
                                                <Printer size={14}/>
                                            </button>
                                        )}
                                    </div>
                                </div>
                            )
                        }) : (
                            <div className="flex flex-col items-center justify-center h-64 text-slate-400">
                                <Layers size={48} className="mb-4 opacity-20"/>
                                <p className="font-medium text-sm">No hay registros para mostrar en esta vista.</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Payment Modal */}
            <Modal isOpen={isPaymentModalOpen} onClose={() => setIsPaymentModalOpen(false)} title="Registrar Cobro Masivo">
                <div className="space-y-6">
                    <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-2xl text-center border border-slate-100 dark:border-slate-700">
                        <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-2">Total a Cobrar</p>
                        <p className="text-4xl font-black text-brand-navy dark:text-white">${
                            currentList.filter(i => selectedItems.has(`${i.clientId}-${i.period}`)).reduce((s, i) => s + i.amount, 0).toFixed(2)
                        }</p>
                        <p className="text-xs text-slate-500 mt-2">{selectedItems.size} items seleccionados</p>
                    </div>

                    <div>
                        <label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Método de Pago</label>
                        <div className="grid grid-cols-3 gap-2">
                             {['Efectivo', 'Transferencia', 'Cheque'].map(m => (
                                 <button 
                                    key={m}
                                    onClick={() => setPaymentMethod(m)}
                                    className={`py-3 rounded-xl text-xs font-bold border transition-all ${paymentMethod === m ? 'bg-brand-navy text-white border-brand-navy' : 'bg-white border-slate-200 text-slate-500 hover:bg-slate-50'}`}
                                >
                                    {m}
                                </button>
                             ))}
                        </div>
                    </div>

                    <button 
                        onClick={handleProcessPayment} 
                        disabled={isProcessing}
                        className="w-full py-4 bg-emerald-500 hover:bg-emerald-600 text-white font-bold rounded-xl shadow-lg shadow-emerald-500/20 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                    >
                        {isProcessing ? <Loader className="animate-spin"/> : <CheckCircle size={20}/>}
                        <span>Confirmar Cobro</span>
                    </button>
                </div>
            </Modal>
            
            {/* Receipt Modal */}
            <Modal isOpen={isReceiptOpen} onClose={() => setIsReceiptOpen(false)} title="Comprobante Generado">
                {receiptData && (
                    <div className="text-center p-4">
                        <div className="w-16 h-16 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto mb-4">
                            <CheckCircle size={32}/>
                        </div>
                        <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-2">¡Pago Registrado!</h3>
                        <p className="text-slate-500 text-sm mb-6">El cobro se ha guardado correctamente y el estado de los clientes ha sido actualizado.</p>
                        <div className="flex gap-3">
                             <button onClick={() => printSalesNote(receiptData, businessProfile)} className="flex-1 py-3 bg-brand-navy text-white font-bold rounded-xl flex items-center justify-center gap-2">
                                <Printer size={18}/> Imprimir
                             </button>
                             <button onClick={() => setIsReceiptOpen(false)} className="px-6 py-3 bg-slate-100 text-slate-600 font-bold rounded-xl hover:bg-slate-200">
                                Cerrar
                             </button>
                        </div>
                    </div>
                )}
            </Modal>

        </div>
    );
};
